#!/bin/sh

log()   { STEP="$*"; sudo_refresh; echo "--> $*"; }
logk()  { STEP="";   echo "OK"; }

# Install oh-my-zsh
if [ ! -d ~/.oh-my-zsh ]; then
  log "Installing ohmyzsh:"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  git clone --recursive https://github.com/joel-porquet/zsh-dircolors-solarized $ZSH_CUSTOM/plugins/zsh-dircolors-solarized
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  logk
fi

# Install fonts
if [ ! -f "$HOME/Library/Fonts/Meslo LG S Regular for Powerline.ttf" ]; then
  log "Installing Font: Meslo LG S Regular for Powerline"
  wget -nc -P "$HOME/Library/Fonts" https://github.com/powerline/fonts/raw/master/Meslo%20Slashed/Meslo%20LG%20S%20Regular%20for%20Powerline.ttf
  logk
fi
if [ ! -f "$HOME/Library/Fonts/Meslo LG M Regular for Powerline.ttf" ]; then
  log "Installing Font: Meslo LG M Regular for Powerline"
  wget -nc -P "$HOME/Library/Fonts" https://github.com/powerline/fonts/raw/master/Meslo%20Slashed/Meslo%20LG%20M%20Regular%20for%20Powerline.ttf
  logk
fi

# Restore Mackup configs
mackup restore

# Install latest node LTS via NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # load nvm
nvm install --lts --latest-npm
